### ISSUE TITLE
Can't overwrite saved games

### ISSUE THREAD

**Issue by bladeSk** [fgsfdsfgs/QuakespasmNX#5]
New save games can be created, but overwriting works only until you load a save or quit. After that, attempting to overwrite an old slot results in `Error: couldn't open`.

I'm on HOS 10.2.0 + Atmosphére 0.14.4.

Unrelated suggestion - it would be nice to have the crosshair on by default (`crosshair="1"`).

**Comment by fgsfdsfgs** [comment]
That's weird. Maybe rebuilding with the newest libnx would fix that.

**Comment by bladeSk** [comment]
Yep, that's entirely possible. Other than this, kudos for how flawlessly the port works. Especially the gyro aiming is implemented very well and it's a ton of fun. The other ports have bad controls and are riddled with issues.

**Comment by bladeSk** [comment]
Tried the latest version - 0.4.0 and the issue still persists.

**Comment by fgsfdsfgs** [comment]
That is extremely weird and I don't like it. `fopen()` just fucking fails for no reason at all for saves that already exist. They have write permissions, they aren't open by something else and the files are most definitely there.
UPDATE: The load game function does actually forget to close the files.

**Comment by fgsfdsfgs** [comment]
@bladeSk Can you check if this solves the problem?
[quakespasmnx.zip](https://github.com/fgsfdsfgs/QuakespasmNX/files/6517557/quakespasmnx.zip)

**Comment by bladeSk** [comment]
It does! Saving worked in all cases I tried. Good job with the fix.

**Comment by fgsfdsfgs** [comment]
Thanks, I'll make a release shortly.
