### ISSUE TITLE
Doesn’t work in OFW 12.0.0 | ams 0.19.1

### ISSUE THREAD

**Issue by cucholix** [fgsfdsfgs/QuakespasmNX#6]
Updated my Switch to OFW 12.0.0 | ams 0.19.1, and the game throws: “An error has occurred closing software”

**Comment by fgsfdsfgs** [comment]
Looks like it didn't break "some" homebrew, it fucking broke all of it.

**Comment by fgsfdsfgs** [comment]
Should be fixed with 0.4.0. Please test.

**Comment by cucholix** [comment]
Just tested in OFW 12.0.1 | ams 19.0.1, works fine
